using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSI2441.A2.Web.MVC.Models
{
    /**
     * Student superclass.
     */
    public class StudentModel
    {
        [Required(ErrorMessage = "Required")]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        // Generated by DB, may use for temp storage, else remove if redundant.
        // TODO: Add method at controller to retrieve generated ID.
        public string StudentID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date of birth")]
        public DateTime Dob { get; set; }

        // Generated by controller, may use for temp storage, else remove if redundant.
        // TODO: Add method at controller to generate 
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Landline")]
        public string Landline { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Mobile")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Postcode")]
        public string Postcode { get; set; }
    }
}