using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSI2441.A2.Web.MVC.Models
{
    /*******************
     * MANAGE STUDENTS *
     *******************/

    public class AddStudentViewModel
    {
        [Required(ErrorMessage = "Required")]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        // public string studentID { get; set; } being generated by db

        // [Required(ErrorMessage = "Required")] redundant, has datepicker editor
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date of birth")]
        public DateTime Dob { get; set; }

        // public string email { get; set; } being generated by db

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Landline")]
        public string Landline { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Mobile")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Postcode")]
        public string Postcode { get; set; }
    }

    public class SearchStudentViewModel
    {
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Search method")]
        public string SearchMethod { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Search string")]
        public string SearchString { get; set; }

        // may need separate fields for ID and name...
    }

    public class EditStudentViewModel : SearchStudentViewModel
    {

    }

    public class DeleteStudentViewModel : SearchStudentViewModel
    {

    }

    public class ManageUnitViewModel
    {
        
    }

    public class ManageCourseViewModel
    {
        
    }

    public class ManageResultViewModel
    {
        
    }
}