using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSI2441.A2.Web.MVC.Models
{
    public class ManageStudentViewModel
    {
        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        // public string studentID { get; set; } being generated by db

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date of birth")]
        public DateTime Dob { get; set; }

        // public string email { get; set; } being generated by db

        
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
    }

    public class ManageUnitViewModel
    {
        
    }

    public class ManageCourseViewModel
    {
        
    }

    public class ManageResultViewModel
    {
        
    }
}