//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace A2.University.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseEnrolments = new HashSet<CourseEnrolment>();
        }
    
        [Display(Name = "Course ID")]
        [Required(ErrorMessage = "The Course ID field is required.")]
        [RegularExpression("([A-Z]{1}[0-9]{2})", ErrorMessage = "Must be a valid Unit ID.")]
        public string course_id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "The Title field is required.")]
        [RegularExpression("(^[a-zA-Z0-9\\.\\,\\# ]{5,}$)", ErrorMessage = "Must be a valid Title.")]
        public string title { get; set; }

        [Display(Name = "Coordinator")]
        [Required(ErrorMessage = "The Coordinator field is required.")]
        public long coordinator_id { get; set; }

        [Display(Name = "Course Type")]
        [Required(ErrorMessage = "The Course Type field is required.")]
        public long course_type_id { get; set; }

        // SelectListItems used for ViewData, see Controller
        public IEnumerable<SelectListItem> Coordinators { get; set; }
        public IEnumerable<SelectListItem> CourseTypes { get; set; }

        public virtual CourseType CourseType { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseEnrolment> CourseEnrolments { get; set; }
    }
}
