//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2.University.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long student_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime dob { get; set; }
        public string email { get; set; }
        public string ph_landline { get; set; }
        public string ph_mobile { get; set; }
        public string adrs { get; set; }
        public string adrs_city { get; set; }
        public string adrs_state { get; set; }
        public int adrs_postcode { get; set; }
    }
}
