//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2.University.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentUser
    {
        public long student_user_id { get; set; }
        public long student_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
