//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2.University.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public string unit_id { get; set; }
        public string title { get; set; }
        public long coodinator_id { get; set; }
        public int credit_points { get; set; }
        public long unit_type_id { get; set; }
    }
}
