using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FluentValidation.Attributes;

namespace A2.University.Web.Models
{
    /// <summary>
    /// StudentAccount base view model.
    /// </summary>
    public class StudentAccountBaseViewModel
    {
        // generated by db
        public long StudentUserId { get; set; }

        // fk
        public long StudentId { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Remember")]
        public bool RememberMe { get; set; }

        // default = STUDENT, hidden from user
        public string Role { get; set; }
    }

    /// <summary>
    /// StudentAccount Login view model.
    /// </summary>
    [Validator(typeof(StudentLoginViewModelValidator))]
    public class StudentLoginViewModel : StudentAccountBaseViewModel
    {
        // no custom fields required.
    }

    /// <summary>
    /// StudentAccount Register view model.
    /// </summary>
    [Validator(typeof (StudentRegisterViewModelValidator))]
    public class StudentRegisterViewModel : StudentAccountBaseViewModel
    {
        // Sets default role, since Staff login not required.
        public StudentRegisterViewModel()
        {
            // default role
            Role = "STUDENT";
        }
    }
}